/*
 * ApendoServer.java
 *
 * Created on 08 November 2000, 22:13
 */

package apendoMan.server;

import apendoMan.*;
import apendoMan.networking.*;

/**
 *
 * @author  Kolonel Kustard
 * @version
 */
public class ApendoServerWindow extends javax.swing.JFrame {
    
    StartServer server;
    ServerClientThread serverClientThread;

    /** Creates new form ApendoServer */
    public ApendoServerWindow() {
        initComponents ();
        pack ();
        this.setSize(640, 480);
        this.show();
    }
    
    private void startServerClient() {
        serverClientThread = new ServerClientThread(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        startGameButton = new javax.swing.JButton();
        outputBox = new java.awt.TextArea();
        label1 = new java.awt.Label();
        startServerButton = new javax.swing.JButton();
        createSClient = new javax.swing.JCheckBox();
        getContentPane().setLayout(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        startGameButton.setText("Start Game");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGame(evt);
            }
        }
        );
        
        getContentPane().add(startGameButton);
        startGameButton.setBounds(60, 130, 100, 30);
        
        
        outputBox.setBackground(new java.awt.Color (212, 208, 200));
        outputBox.setEditable(false);
        outputBox.setFont(new java.awt.Font ("Dialog", 0, 11));
        outputBox.setForeground(java.awt.Color.black);
        
        getContentPane().add(outputBox);
        outputBox.setBounds(230, 70, 370, 280);
        
        
        label1.setFont(new java.awt.Font ("Arial", 1, 14));
        label1.setBackground(new java.awt.Color (204, 204, 204));
        label1.setForeground(java.awt.Color.black);
        label1.setText("Welcome to the ApendoServer Application");
        
        getContentPane().add(label1);
        label1.setLocation(140, 10);
        label1.setSize(label1.getPreferredSize());
        
        
        startServerButton.setText("Start Server");
        startServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServer(evt);
            }
        }
        );
        
        getContentPane().add(startServerButton);
        startServerButton.setBounds(60, 90, 100, 30);
        
        
        createSClient.setSelected(true);
        createSClient.setText("Create Server Client (controls physics)");
        
        getContentPane().add(createSClient);
        createSClient.setLocation(10, 180);
        createSClient.setSize(createSClient.getPreferredSize());
        
    }//GEN-END:initComponents

  private void startServer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServer
      startServerButton.setEnabled(false);
      server = new StartServer(outputBox, createSClient.isSelected());
      if (createSClient.isSelected()) startServerClient();
  }//GEN-LAST:event_startServer

  private void startGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGame
      startGameButton.setEnabled(false);
      server.startGame();
  }//GEN-LAST:event_startGame

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startGameButton;
    private java.awt.TextArea outputBox;
    private java.awt.Label label1;
    private javax.swing.JButton startServerButton;
    private javax.swing.JCheckBox createSClient;
    // End of variables declaration//GEN-END:variables

}
